### ISSUE TITLE
Mettre en place les renvois 

### ISSUE THREAD

**Issue by sardinecan** [publicarchi/ledouxIndexing#3]
avec un élément `<ref corresp="#idref"/>`

**Comment by sardinecan** [comment]
@emchateau, quelques questions concernant les renvois…
- un concept peut-il  renvoyer vers plusieurs concepts ?
```xml
<item xml:id="conceptB">
   <label>Concept B</label>
   <ref corresp="#conceptA"/>
   <ref corresp="#conceptC"/>
</item>
```
- un concept qui renvoie vers un autre concept peut-il tout de même disposer de ptr ?
```xml
<item xml:id="conceptB">
   <label>Concept B</label>
   <linkGrp>
      <ptr target="//*[@id='paragraphe-14']" offset="42" length="23" type="x-pointer"/>
   </linkGrp>
   <ref corresp="#conceptA"/>
</item>
```
Si non, faut-il prévoir un mécanisme de copie automatique des `<ptr/>` ? C'est facile à faire, mais j'ai peur qu'en cas d'erreur de manipulation cela entraine des conséquences qui soient difficilement réparables, du style impossibilité de retrouver les `<ptr/>` qui auraient été transférés par erreur…

**Comment by sardinecan** [comment]
> ```xml
> <item xml:id="conceptB">
>    <label>Concept B</label>
>    <ref corresp="#conceptA"/>
>    <ref corresp="#conceptC"/>
> </item>
> ```

Ou alors, il est aussi possible d'avoir plusieurs valeurs dans `@corresp` :
```xml
<item xml:id="conceptB">
   <label>Concept B</label>
   <ref corresp="#conceptA #conceptC"/>
</item>
```
En revanche, côté design cela nécessite d'avoir, pour chaque renvoi, des `checkbox` comportant la liste de tous les concepts — là où pour chaque `<ref/>` nous n'aurions eu qu'une liste déroulante, un peu plus minimaliste. Sauf si on fait une fenêtre modale pour "cacher" un peu les choses.

**Comment by sardinecan** [comment]
Pour le moment je suis parti sur la répétition d'éléments `<ref/>`, sans recopie des `<ptr/>` (qui me semble trop hasardeuse). C'est fonctionnel.

**Comment by emchateau** [comment]
Salut,
Non un renvoi renvoie seulement à un autre concept et normalement un seul.

**Comment by sardinecan** [comment]
Salut, 
Ok donc un seul renvoi possible par concept ?

**Comment by sardinecan** [comment]
done
